name: Api Integration Tests

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up Swagger Petstore - OpenAPI 3.0
        run: |
         docker pull swaggerapi/petstore3:unstable
         docker run  --name swaggerapi-petstore3 -d -p 8080:8080 swaggerapi/petstore3:unstable
